version: '3.1'

services:
  db:
    container_name: minir-place-db
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
